GET http://localhost:5254/games
###
POST http://localhost:5254/games
content-type : application/json

{
    "Id" : 6,
    "Name" : "fifa27",
    "Description" : "new relese from EA",
    "Price" : "59.99",
    "ReleaseDate" : "2026-09-01"
}

###
Content-Type: application/json

{
    
    "Name" : "PES26",
    "Description" : "new relese from EA",
    "Price" : "59.99",
    "ReleaseDate" : "2026-09-01"
}

###

PUT http://localhost:5254/games/2
Content-Type: application/json

{
    
    "Name" : "PES26",
    "Description" : "new relese from EA",
    "Price" : "59.99",
    "ReleaseDate" : "2026-09-01"
}
###

DELETE http://localhost:5254/games/6